### ISSUE TITLE


### ISSUE THREAD

**Issue by mindcat** [icefoxen/arewestdlibyet#2]
maul
rocket.rs
piston
...

I see cargo really needs a tag system.

**Comment by icefoxen** [comment]
There appears to be no crate named `maul`.

Rocket is somewhat tempting.

When we can point to a single crate named `piston` which actually does useful things better than the alternatives I'll include it.  (I'm kind of biased though.)

**Comment by mindcat** [comment]
Sorry, nevermind.

**Comment by icefoxen** [comment]
No, thanks for the suggestions!  :-)

**Comment by mindcat** [comment]
I just about I didn't to think then submit the topic, that, so I say nevermind it =S
